data:
    train_data_path: "data/toy/train"
    dev_data_path: "data/toy/dev"
    test_data_path: "data/toy/test"
    dataset_type: "plain"
    src:
        language: "de"
        level: "word" # word bpe
        tokenizer_type: "sentencepiece" # subword-nmt sentencepiece
        vocab_min_freq: 1
        vocab_max_size: 50000
        lowercase: True
        normalize: True # tokernizer pre-process sentence.strip()
        max_length: 100
        min_length: 1
        filter_or_truncate: "truncate"
    trg: 
        language: "en"
        level: "word"
        tokenizer_type: "sentencepiece"
        vocab_min_freq: 1
        vocab_max_size: 30000
        lowercase: True
        normalize: True 
        max_length: 50
        min_length: 1
        filter_or_truncate: "truncate"

training:
    model_dir: "models/rencos_python/test10"
    tensorboard_dir: "models/tensorboard_log/rencos_python_test10"
    overwrite: True
    random_seed: 980820
    use_cuda: True
    num_workers: 0
    optimizer: "adam"
    adam_betas: [0.9, 0.999]
    normalization: "batch" # batch,tokens | batch means loss divide sentences in the batch; token means loss divide tokens in the batch.
    loss: "CrossEntropy"
    label_smoothing: 0.0
    scheduling: "StepLR" # "ReduceLROnPlateau", "StepLR", "ExponentialLR"
    mode: "max"  # for schedule="ReduceLROnPlateau"
    factor: 0.5 # for schedule="ReduceLROnPlateau"
    patience: 5 # for scheduling = 'ReduceLROnPlatea'
    step_size: 5 # for scheduling = "StepLR" 
    gamma: 0.8 # for scheduling = "StepLR" or "ExponentialLR"
    learning_rate: 0.005
    weight_decay: 0
    learning_rate_min: 0.000001
    keep_best_ckpts: 5
    logging_freq: 10
    validation_freq: 5 # unit:epochs
    log_valid_sentences: [0,1,2]
    early_stopping_metric: "bleu"
    shuffle: True
    epochs: 30
    max_updates: 100000 #  "np.inf"
    batch_size: 32
    batch_type: "sentence"
    # load_model: None
    reset_best_ckpt: False
    reset_scheduler: False
    reset_optimizer: False
    reset_iter_state: False
    clip_grad_val: 1
    # clip_grad_norm:

testing:
    batch_size: 64
    batch_type: "sentence"
    max_output_length: 30
    min_output_length: 1
    eval_metrics: ['bleu', 'meteor','rouge-l']
    n_best: 1
    beam_size: 5
    beam_alpha: -1
    return_attention: False
    return_prob: "hypotheses" # hypotheses, references, none
    generate_unk: True
    repetition_penalty: 2 # >1, -1 means no repetition penalty. # no implemented
    no_repeat_ngram_size: -1 # no implemented


model:
    initializer: "xavier_normal"     # xavier_uniform xavier_normal uniform normal
    init_gain: 1.0 # for xavier
    init_weight: 0.01 # for uniform normal
    embed_initializer: "xavier_normal"
    embed_init_gain: 1.0 # for xavier
    embed_init_weight: 0.01
    bias_initializer: "zeros"
    bias_init_weight: 0.01
    tied_softmax: False
    tied_embeddings: False
    copy: True  # for copy mechanism
    encoder:
        model_dim: 64
        ff_dim: 128
        num_layers: 3
        head_count: 4
        layer_norm_position: "pre"
        freeze: False
        dropout: 0.1
        embeddings:
            embedding_dim: 64
            scale: True
            freeze: False
            dropout: 0.1
            # load_pretrained
        src_pos_emb: "absolute" # use positional embeddings in encoder "absolute", "learnable","relative"
        max_src_len: 100 # for learnable. keep same with data segment
        max_relative_position: 16  # only for relative position, else must be set to 0
        use_negative_distance: True # for relative position
    decoder:
        model_dim: 64
        ff_dim: 128
        num_layers: 3
        head_count: 4
        layer_norm_position: "pre"
        freeze: False
        dropout: 0.1
        embeddings:
            embedding_dim: 64
            scale: True
            freeze: False
            dropout: 0.1
            # load_pretrained
        trg_pos_emb: "absolute" # use positional embeddings in encoder "absolute", "learnable","relative"
        max_trg_len: 50 # for learnable. keep same with data segment
        max_relative_position: 16  # only for relative position, else must be set to 0
        use_negative_distance: True # for relative position