data:
    train_data_path: "data/rencos_python/train"
    dev_data_path: "data/rencos_python/valid"
    test_data_path: "data/rencos_python/test"
    dataset_type: "plain"
    src:
        language: "code"
        level: "word" # word bpe
        tokenizer_type: "sentencepiece" # subword-nmt sentencepiece
        vocab_min_freq: 1
        vocab_max_size: 50000
        lowercase: True
        normalize: True # tokernizer pre-process sentence.strip()
        max_length: 100
        min_length: 1
        filter_or_truncate: "truncate"
    trg: 
        language: "summary"
        level: "word"
        tokenizer_type: "sentencepiece"
        vocab_min_freq: 1
        vocab_max_size: 30000
        lowercase: True
        normalize: True 
        max_length: 50
        min_length: 1
        filter_or_truncate: "truncate"

training:
    model_dir: "models/rencos_python/test1"
    tensorboard_dir: "models/tensorboard_log/rencos_python_test1"
    overwrite: True
    random_seed: 980820
    use_cuda: True
    num_workers: 4
    normalization: "batch" # batch,tokens | batch means loss divide sentences in the batch; token means loss divide tokens in the batch.
    loss: "CrossEntropy"
    label_smoothing: 0.0
    scheduling: "ExponentialLR" # "ReduceLROnPlateau", "StepLR", "ExponentialLR"
    mode: "max"  # for schedule="ReduceLROnPlateau"
    factor: 0.5 # for schedule="ReduceLROnPlateau"
    patience: 5 # for scheduling = 'ReduceLROnPlatea'
    step_size: 5 # for scheduling = "StepLR" 
    gamma: 0.1 # for scheduling = "StepLR" or "ExponentialLR"
    learning_rate_min: 1.0e-8
    keep_best_ckpts: 5
    logging_freq: 100
    validation_freq: 1000
    log_valid_sentences: [0,1,2]
    early_stopping_metric: "bleu"
    shuffle: True
    epochs: 100
    max_updates: "np.inf"
    batch_size: 32
    batch_type: "sentence"
    # load_model: None
    reset_best_ckpt: False
    reset_scheduler: False
    reset_optimizer: False
    reset_iter_state: False
    # clip_grad_val: 
    # clip_grad_norm:

testing:
    batch_size: 64
    batch_type: "sentence"
    max_output_length: 30
    min_output_length: 1
    eval_metrics: ['bleu', 'meteor','rouge-l']
    n_best: 1
    beam_size: 5
    beam_alpha: -1
    return_attention: False
    return_prob: "hyp" # hyp, ref, none
    generate_unk: True
    repetition_penalty: 2 # >1, -1 means no repetition penalty.
    no_repeat_ngram_size: -1


model:
    initializer: "xavier_uniform"     # xavier_uniform xavier_normal uniform normal
    init_gain: 1.0 # for xavier
    init_weight: 0.01 # for uniform normal
    embed_initializer: "normal"
    embed_init_gain: 1.0 # for xavier
    embed_init_weight: 0.01
    bias_initializer: "zeros"
    bias_init_weight: 0.01
    tied_softmax: False
    tied_embeddings: False
    encoder:
        model_dim: 512
        ff_dim: 2048
        num_layers: 6
        head_count: 8
        layer_norm_position: "post"
        freeze: False
        dropout: 0.1
        embeddings:
            embedding_dim: 512
            scale: True
            freeze: False
            dropout: 0.1
            # load_pretrained
    decoder:
        model_dim: 512
        ff_dim: 2048
        num_layers: 6
        head_count: 8
        layer_norm_position: "post"
        freeze: False
        dropout: 0.1
        embeddings:
            embedding_dim: 512
            scale: True
            freeze: False
            dropout: 0.1
            # load_pretrained